import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/Recipe-Provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
      <ThemeProvider>
          <Navbar/>
      </ThemeProvider>
        {children}
      </body>
    </html>
  )
}
